from .HelpCommand import HelpCommand
from .CubeCommand import CubeCommand
from .CircleCommand import CircleCommand
from .CircleQualityCommand import CircleQualityCommand
from .ConeCommand import ConeCommand
from .CuboidCommand import CuboidCommand
from .PyramidCommand import PyramidCommand
from .SphereCommand import SphereCommand
from .ResetCommand import ResetCommand
from .CylinderCommand import CylinderCommand
from .AutorotationCommand import AutorotationCommand
from .ColorCommand import ColorCommand
from .LineColorCommand import LineColorCommand
from .RotationQualityCommand import RotationQualityCommand
from .ContextCommand import ContextCommand
from .PrintFiguresCommand import PrintFiguresCommand
from .CameraFarCommand import CameraFarCommand
from .CameraNearCommand import CameraNearCommand
from .ReadFigureCommand import ReadFigureCommand
from .ExportCommand import ExportCommand
from .ChangeCameraCommand import ChangeCameraCommand
from .RemoveCommand import RemoveCommand
from .TriangleCommand import TriangleCommand
from .DebugCommand import DebugCommand
from .LineCommand import LineCommand